# Generated by Django 4.0.4 on 2022-05-27 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0002_contact_topic_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
        migrations.AddField(
            model_name='topic',
            name='identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
