# Generated by Django 4.0.4 on 2022-05-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0004_remove_topic_identifier_alter_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
