# Generated by Django 4.0.4 on 2022-06-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0008_remove_topic_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
