# Generated by Django 4.0.4 on 2022-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0009_delete_contact_delete_family_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
